// Ilha 2 — 50 novos biomas endgame. Todos com nível de perigo >= 100.
// Cada bioma tem 3 andares de profundidade (implementado no engine via
// activeFloor 1..3 quando o jogador está na Ilha 2).
//
// Alguns nomes se repetem propositalmente (como "Floresta") — apenas os que
// naturalmente também apareceriam no mundo original.

import type { Biome } from "./engine";

function ct(label: string, floor: string, wall: string, accent: string, monsters: string[], boss: string) {
  return { label, floor, wall, accent, monsters, boss };
}

// IDs começam em 201 para não colidir com o mundo original (1..80).
export const ISLAND2_BIOMES: Biome[] = [
  { id: 201, name: "Floresta Titânica",          color: "#1e5030", accent: "#0e2818", danger: 100, monsters: ["Titã Verde", "Aranha Colossal", "Ent Ancião"],           boss: "Rei da Floresta Titânica",
    caveTheme: ct("Raízes Titânicas", "#0a1810", "#040804", "#40a060", ["Larva Titânica", "Broto Sombrio", "Aranha Menor"], "Coração de Raiz") },
  { id: 202, name: "Praia Amaldiçoada",           color: "#c8b070", accent: "#7a5a2a", danger: 100, monsters: ["Caranguejo Espectral", "Marinheiro Podre", "Kraken Menor"], boss: "Almirante Amaldiçoado",
    caveTheme: ct("Gruta da Maré", "#1a2028", "#080a10", "#a0d0e0", ["Peixe Fantasma", "Coral Vivo", "Sereia Sombria"], "Kraken Coralino") },
  { id: 203, name: "Vulcão Cataclísmico",         color: "#c02020", accent: "#601010", danger: 110, monsters: ["Balrog Menor", "Salamandra Titã", "Diabo do Magma"],    boss: "Titã do Cataclismo",
    caveTheme: ct("Câmara Cataclísmica", "#280808", "#100404", "#ff4020", ["Chama Viva", "Servo Ígneo", "Elemental Fundido"], "Coração Cataclísmico") },
  { id: 204, name: "Deserto Petrificado",         color: "#9a7a50", accent: "#4a3820", danger: 105, monsters: ["Gólem de Osso", "Serpente Fossilizada", "Escorpião Titã"], boss: "Faraó Petrificado",
    caveTheme: ct("Tumba Petrificada", "#2a1c10", "#100806", "#c89060", ["Múmia Titânica", "Escaravelho Petrificado", "Sacerdote Fóssil"], "Faraó Ancião") },
  { id: 205, name: "Montanhas Ancestrais",        color: "#707078", accent: "#303038", danger: 108, monsters: ["Gigante de Pedra", "Águia Titânica", "Ogro Ancião"],   boss: "Colosso Ancestral",
    caveTheme: ct("Coração da Montanha", "#1a1a20", "#080810", "#a0a0b0", ["Kobold Titã", "Golem Menor", "Verme das Rochas"], "Titã Interior") },
  { id: 206, name: "Pântano dos Titãs",           color: "#3a4a2a", accent: "#182010", danger: 112, monsters: ["Hidra Ancestral", "Bruxa Titã", "Zumbi Colossal"],     boss: "Hidra dos Titãs",
    caveTheme: ct("Cripta do Lodo Antigo", "#101810", "#040804", "#5aa050", ["Verme Titânico", "Bruxa Menor", "Slime Colossal"], "Hidra Menor") },
  { id: 207, name: "Tundra Eterna",               color: "#c0d8e0", accent: "#607080", danger: 115, monsters: ["Mamute Espectral", "Lobo Titã", "Draugr Ancião"],      boss: "Imperador Eterno",
    caveTheme: ct("Caverna Eterna", "#20303a", "#0a1418", "#a0c8e0", ["Espectro Eterno", "Aranha do Gelo Titã", "Draugr Menor"], "Rei do Gelo Eterno") },
  { id: 208, name: "Cordilheira Draconiana",      color: "#8090a8", accent: "#40506a", danger: 118, monsters: ["Wyvern Ancião", "Yeti Titã", "Arqueiro Draconiano"],   boss: "Dragão Ancestral",
    caveTheme: ct("Câmara do Dragão Ancião", "#181828", "#08080f", "#a0b0d0", ["Filhote Ancião", "Yeti Menor", "Espírito Draconiano"], "Dragão Cosmico") },
  { id: 209, name: "Selva Primordial",            color: "#2a6a2a", accent: "#0f3010", danger: 108, monsters: ["Onça Titã", "Naga Ancestral", "Caçador Primordial"],   boss: "Altar Primordial",
    caveTheme: ct("Templo Primordial", "#101810", "#040804", "#40a040", ["Naga Menor", "Onça Espectral", "Ídolo Titã"], "Sacerdote Primordial") },
  { id: 210, name: "Floresta Sanguinária",        color: "#602020", accent: "#280808", danger: 120, monsters: ["Lobisomem Titã", "Fada Sanguinária", "Cervo Sombrio Ancião"], boss: "Rei Sanguinário",
    caveTheme: ct("Covil Sanguinário", "#280808", "#100404", "#d04040", ["Lobisomem Menor", "Vampiro Ancião", "Fada Amaldiçoada"], "Alfa Sanguinário") },
  { id: 211, name: "Ilha das Cinzas",             color: "#403830", accent: "#181410", danger: 122, monsters: ["Fênix Titã", "Cão Ígneo Ancião", "Espírito de Cinzas"], boss: "Fênix Ancestral Titã",
    caveTheme: ct("Cratera Titânica", "#201814", "#0c0806", "#c08060", ["Cão de Cinzas Titã", "Salamandra Ancestral", "Espectro Titã"], "Fênix Menor Titã") },
  { id: 212, name: "Mar Congelado",               color: "#7098b8", accent: "#204060", danger: 124, monsters: ["Kraken do Gelo", "Sereia Congelada", "Homem-Peixe Titã"], boss: "Leviatã Congelado",
    caveTheme: ct("Gruta Congelada", "#0a1a28", "#040a10", "#4090c0", ["Anguíla do Gelo", "Casco Congelado", "Marinheiro Gélido"], "Leviatã Menor") },
  { id: 213, name: "Cavernas Prismáticas",        color: "#a080e8", accent: "#402860", danger: 126, monsters: ["Gólem Prismático", "Aranha de Ametista Titã", "Minerador Ancião"], boss: "Rainha Prismática",
    caveTheme: ct("Geoda Prismática", "#20182a", "#0a0810", "#c090ff", ["Cristal Menor", "Larva Prismática", "Ecoador Titã"], "Coração Prismático") },
  { id: 214, name: "Penhascos Divinos",           color: "#d8e0f0", accent: "#7080a0", danger: 128, monsters: ["Serafim Menor", "Servo Angelical Titã", "Gárgula Ancestral"], boss: "Serafim Titã",
    caveTheme: ct("Santuário Divino", "#20242c", "#0c1014", "#d0d8e8", ["Gárgula Menor", "Coro Divino", "Anjo Ancião"], "Herald Titã") },
  { id: 215, name: "Vale dos Ventos Eternos",     color: "#a0c890", accent: "#405030", danger: 130, monsters: ["Elemental do Vento Titã", "Wyvern Titã", "Ladrão do Vento Ancião"], boss: "Roc Ancestral",
    caveTheme: ct("Câmara Sussurrante Titã", "#181c14", "#08100a", "#a0c088", ["Espírito Sibilante Titã", "Morcego Titã", "Assobio Vivo Ancião"], "Vórtice Ancestral") },
  { id: 216, name: "Campos Sombrios",             color: "#4a4028", accent: "#181008", danger: 132, monsters: ["Espantalho Titã", "Rato Titânico", "Camponês Amaldiçoado Ancião"], boss: "Ceifador Titã",
    caveTheme: ct("Adega Sombria", "#20180c", "#0c0804", "#a08040", ["Rato Ancião", "Espantalho Menor Titã", "Camponês Podre Titã"], "Ceifador Menor Titã") },
  { id: 217, name: "Ruínas Divinas",              color: "#a08868", accent: "#503820", danger: 134, monsters: ["Cavaleiro Fantasma Titã", "Estátua Titânica", "Legionário Ancião"], boss: "Imperador Divino",
    caveTheme: ct("Catacumbas Divinas", "#241c14", "#0c0806", "#c0a880", ["Legionário Menor Titã", "Escravo Titã", "Estátua Menor Titã"], "Senador Divino") },
  { id: 218, name: "Reino Sub-Titânico",          color: "#504058", accent: "#20182a", danger: 136, monsters: ["Anão Titã", "Trol Titânico", "Dweller Ancião"], boss: "Rei Sub-Titânico",
    caveTheme: ct("Profundezas Titânicas", "#141020", "#040208", "#807090", ["Verme Titã", "Trol Menor Titã", "Dweller Cego Titã"], "Trono Sub-Titânico") },
  { id: 219, name: "Mar Fumegante",               color: "#605850", accent: "#28221c", danger: 138, monsters: ["Fênix Titânica", "Cão Ígneo Menor Titã", "Espírito de Fumaça Ancião"], boss: "Fênix Fumegante",
    caveTheme: ct("Cratera Fumegante Titã", "#1c1410", "#080604", "#c07050", ["Cão Menor Titã", "Salamandra Fumegante", "Espectro Fumegante"], "Fênix Fumegante Menor") },
  { id: 220, name: "Bosque Luminescente Ancião",  color: "#4a3888", accent: "#20124a", danger: 140, monsters: ["Fada Corrompida Titã", "Cogumelo Titânico", "Vagalume Titã"], boss: "Rainha Luminescente Titã",
    caveTheme: ct("Micélio Profundo Titã", "#100c24", "#040214", "#a880f0", ["Cogumelo Explosivo Titã", "Vagalume Sombrio Titã", "Micomorfe Ancião"], "Rainha Fúngica Titã") },
  { id: 221, name: "Ilha da Tempestade Eterna",   color: "#385070", accent: "#101c34", danger: 142, monsters: ["Elemental de Raio Titã", "Marinheiro Amaldiçoado Ancião", "Harpia Titã"], boss: "Senhor da Tempestade Eterna",
    caveTheme: ct("Câmara do Trovão Eterno", "#0c141c", "#040810", "#80a0f0", ["Elemental Voltaico Titã", "Harpia Menor Titã", "Marujo Voltaico Titã"], "Coração da Tempestade Eterna") },
  { id: 222, name: "Fortaleza Ancestral",         color: "#484858", accent: "#181828", danger: 144, monsters: ["Cavaleiro Caído Titã", "Necromante Ancião", "Lich Titã"], boss: "Rei Caído Titã",
    caveTheme: ct("Masmorra do Rei Titã", "#101018", "#040408", "#a0a0c0", ["Cavaleiro Esqueleto Titã", "Aprendiz Lich Titã", "Servo Necro Titã"], "Príncipe Amaldiçoado Titã") },
  { id: 223, name: "Cânion Titânico",             color: "#a04a28", accent: "#502010", danger: 146, monsters: ["Basilisco Titã", "Bandoleiro Ancião", "Escorpião Titânico"], boss: "Wyrm Titânico",
    caveTheme: ct("Fenda do Wyrm Titã", "#28140c", "#0c0604", "#d05030", ["Basilisco Menor Titã", "Escorpião Menor Titã", "Bandoleiro Titã"], "Wyrm Menor Titã") },
  { id: 224, name: "Picos Divinos",               color: "#c8d4e4", accent: "#5060a0", danger: 148, monsters: ["Dragão Alado Titã", "Monge Divino", "Roc Divino"], boss: "Deus dos Ventos Titã",
    caveTheme: ct("Câmara do Vento Divino", "#1c2028", "#080c10", "#c0d0e8", ["Monge Espectral Titã", "Wyvern Menor Titã", "Roc Jovem Titã"], "Ancião Divino") },
  { id: 225, name: "Jardim Titânico",             color: "#60a860", accent: "#204c20", danger: 150, monsters: ["Ninfa Titã", "Espinho Titânico", "Guardião Floral Ancião"], boss: "Espírito Titânico",
    caveTheme: ct("Raízes Titânicas Ancestrais", "#0c200c", "#040804", "#80d080", ["Raiz Faminta Titã", "Ninfa Menor Titã", "Broto Espinhado Titã"], "Coração Titânico") },
  { id: 226, name: "Cidade Titânica Perdida",     color: "#8a8078", accent: "#40382c", danger: 152, monsters: ["Cidadão Amaldiçoado Titã", "Cão de Guerra Titã", "Ladrão Fantasma Titã"], boss: "Prefeito Titã",
    caveTheme: ct("Esgotos Titânicos", "#181812", "#080804", "#a89880", ["Rato Amaldiçoado Titã", "Ladrão Espectral Titã", "Cidadão Podre Titã"], "Contramestre Titã") },
  { id: 227, name: "Abismo Titânico",             color: "#20182e", accent: "#0a0410", danger: 155, monsters: ["Aberrante Titã", "Tentáculo Titânico", "Devorador Ancião"], boss: "Coisa do Abismo Titã",
    caveTheme: ct("Fenda Impossível Titã", "#0a0410", "#020208", "#6040a0", ["Tentáculo Menor Titã", "Olho Flutuante Titã", "Voraz Cego Titã"], "Devorador Menor Titã") },
  { id: 228, name: "Reino Sombrio Eterno",        color: "#101020", accent: "#040408", danger: 158, monsters: ["Sombra Titã", "Assassino Sombrio Ancião", "Umbra Titã"], boss: "Rei das Sombras Titã",
    caveTheme: ct("Vazio Sombrio Titã", "#040408", "#020204", "#4a4a6a", ["Sombra Vazia Titã", "Assassino Umbra Titã", "Eco Sombrio Titã"], "Príncipe Sombrio Titã") },
  { id: 229, name: "Plano Astral Titânico",       color: "#502878", accent: "#20083a", danger: 160, monsters: ["Vigia Astral Titã", "Estrela Caída Titã", "Fragmento Cósmico Titã"], boss: "Sentinela Cósmico Titã",
    caveTheme: ct("Nexo Astral Titã", "#100824", "#040214", "#a080ff", ["Fragmento Menor Titã", "Vigia Menor Titã", "Eco Astral Titã"], "Sentinela Menor Titã") },
  { id: 230, name: "Trono dos Criadores Titã",    color: "#e8c060", accent: "#a06838", danger: 165, monsters: ["Anjo do Alvorecer Titã", "Herald Titã", "Serafim Titã"], boss: "O Criador Titã",
    caveTheme: ct("Câmara Divina Titã", "#2c2010", "#100804", "#f0d090", ["Herald Menor Titã", "Serafim Menor Titã", "Coro Divino Titã"], "Arauto Titã") },
  { id: 231, name: "Floresta Perdida",            color: "#204a30", accent: "#0a2018", danger: 130, monsters: ["Ent Perdido", "Aranha Perdida", "Elfo Perdido"], boss: "Guardião Perdido",
    caveTheme: ct("Raízes Perdidas", "#101c14", "#040804", "#40a060", ["Aranha das Raízes Titã", "Broto Corrompido Titã", "Traça Verde Titã"], "Aranha-Mãe Perdida") },
  { id: 232, name: "Deserto Ancião",              color: "#c08840", accent: "#805020", danger: 132, monsters: ["Escorpião Ancião", "Múmia Ancião", "Salteador Ancião"], boss: "Faraó Ancestral",
    caveTheme: ct("Tumba Ancestral", "#2a1c10", "#100806", "#c88030", ["Múmia Menor Titã", "Escaravelho Menor Titã", "Sacerdote Menor Titã"], "Faraó Menor Titã") },
  { id: 233, name: "Montanhas Titânicas",         color: "#807888", accent: "#403844", danger: 136, monsters: ["Golem Titânico", "Ogro Titã", "Anão Renegado Titã"], boss: "Colosso Titânico",
    caveTheme: ct("Mina Titânica", "#20202a", "#0c0c14", "#8090b0", ["Kobold Titã Menor", "Golem Menor Titã", "Aranha Metálica Titã"], "Forjador Titânico") },
  { id: 234, name: "Vulcão Adormecido",           color: "#502020", accent: "#200808", danger: 140, monsters: ["Elemental de Lava Titã", "Demônio Menor Titã", "Salamandra Titã Menor"], boss: "Titã Adormecido",
    caveTheme: ct("Forja Adormecida", "#280808", "#100404", "#e05020", ["Diabrete Titã", "Elemental Ígneo Titã", "Salamandra Fundida Titã"], "Senhor do Magma Adormecido") },
  { id: 235, name: "Costa Titânica",              color: "#7098b0", accent: "#304858", danger: 138, monsters: ["Corsário Titã", "Kraken Titã", "Homem-Peixe Titã Menor"], boss: "Almirante Titã",
    caveTheme: ct("Gruta Marinha Titã", "#181c24", "#080a10", "#60a0c0", ["Homem-Peixe Menor Titã", "Marujo Afogado Titã", "Polvo Menor Titã"], "Capitão Titânico") },
  { id: 236, name: "Cavernas Ancestrais",         color: "#8878b8", accent: "#40287a", danger: 142, monsters: ["Golem Ancestral", "Aranha Ancestral", "Minerador Ancestral"], boss: "Rainha Ancestral",
    caveTheme: ct("Geoda Ancestral", "#20182a", "#0a0810", "#a880ff", ["Cristal Andante Titã", "Larva Ancestral", "Ecoador Ancestral"], "Coração Ancestral") },
  { id: 237, name: "Deserto Titânico de Sal",     color: "#e0d0a0", accent: "#a08050", danger: 144, monsters: ["Cristalino Salino Titã", "Nômade Ancião", "Escorpião Branco Titã"], boss: "Rainha do Sal Titã",
    caveTheme: ct("Caverna Salina Titã", "#28201c", "#0c0806", "#e8dcb0", ["Cristal Salino Titã", "Verme das Salinas Titã", "Espectro do Sal Titã"], "Coração Salino Titã") },
  { id: 238, name: "Terras Corrompidas",          color: "#68a028", accent: "#38580c", danger: 148, monsters: ["Mutante Titã", "Ghoul Corrompido", "Cão Corrompido"], boss: "Aberração Corrompida",
    caveTheme: ct("Bunker Corrompido", "#181c18", "#080c08", "#a0ff40", ["Ghoul Menor Titã", "Rato Mutante Titã", "Servo Corrompido Titã"], "Núcleo Corrompido") },
  { id: 239, name: "Cemitério dos Titãs",         color: "#484048", accent: "#181418", danger: 150, monsters: ["Esqueleto Titã", "Cão Necrótico Titã", "Necrofago Titã"], boss: "Coveiro dos Titãs",
    caveTheme: ct("Cripta Titânica", "#141018", "#040208", "#c0b0d0", ["Esqueleto Menor Titã", "Ghoul Sepulto Titã", "Espectro Cadavérico Titã"], "Lich Titânico") },
  { id: 240, name: "Ilhas Flutuantes Titã",       color: "#68a0c0", accent: "#284858", danger: 152, monsters: ["Wyvern Titã Menor", "Servo do Vento Titã", "Piloto Titã"], boss: "Skywhale Titã",
    caveTheme: ct("Câmara Suspensa Titã", "#141c24", "#08080f", "#a0d0f0", ["Servo do Vento Menor Titã", "Espírito Nublado Titã", "Djinn Menor Titã"], "Djinn Titã") },
  { id: 241, name: "Grutas Titânicas",            color: "#a0a8b0", accent: "#484c58", danger: 154, monsters: ["Elemental Líquido Titã", "Espelho Titã", "Alquimista Titã"], boss: "Prisma Titânico",
    caveTheme: ct("Lago Titânico", "#181820", "#080810", "#d0d8e0", ["Poça Líquida Titã", "Espelho Menor Titã", "Reflexo Sombrio Titã"], "Titã do Mercúrio Ancestral") },
  { id: 242, name: "Planalto Titânico",           color: "#8060a0", accent: "#402048", danger: 156, monsters: ["Mycon Titã", "Esporo Titã", "Guardião Titã"], boss: "Colônia Titânica",
    caveTheme: ct("Micélio Titânico", "#141018", "#040208", "#c090e0", ["Esporo Titã Menor", "Mycon Menor Titã", "Sombra Fúngica Titã"], "Rainha Fúngica Ancestral") },
  { id: 243, name: "Ruínas Titânicas Cristalinas", color: "#a8c8d8", accent: "#4870a0", danger: 158, monsters: ["Estátua de Prisma Titã", "Guardião Titã Ancião", "Vidro Vivo Titã"], boss: "Arquiteto Titânico",
    caveTheme: ct("Sanctum Titânico", "#141c20", "#080c10", "#c0e8f0", ["Fragmento Titã", "Guardião Menor Titã", "Prisma Sombrio Titã"], "Sanctum Titã Ancião") },
  { id: 244, name: "Vastidão Titânica",           color: "#502828", accent: "#201010", danger: 162, monsters: ["Devorador Titã", "Boca Titânica", "Tentáculo Titã"], boss: "Fauces Titânicas",
    caveTheme: ct("Estômago Titânico", "#180c0c", "#080404", "#a04040", ["Órgão Titã", "Verme Digestivo Titã", "Ácido Titã"], "Fauces Menores Titã") },
  { id: 245, name: "Bosque Titânico Espectral",   color: "#284848", accent: "#101c1c", danger: 164, monsters: ["Assombração Titã", "Cervo Espectral Titã", "Wisp Titã"], boss: "Senhora Titânica dos Espectros",
    caveTheme: ct("Cripta Titânica Espectral", "#101818", "#040808", "#80c0c0", ["Wisp Menor Titã", "Aparição Titã", "Servo Espectral Titã"], "Espectro Titânico Ancestral") },
  { id: 246, name: "Núcleo Titânico do Mundo",    color: "#a03010", accent: "#501004", danger: 170, monsters: ["Elemental Primal Titã", "Coração de Magma Titã", "Titã Menor Ancestral"], boss: "Coração Titânico do Mundo",
    caveTheme: ct("Câmara Titânica do Núcleo", "#180404", "#080202", "#ff6020", ["Chama Primal Titã", "Servo Titânico", "Elemental Fundido Titã"], "Núcleo Titã Ancião") },
  { id: 247, name: "Oásis Titânico",              color: "#c8c090", accent: "#786840", danger: 172, monsters: ["Fada Titânica", "Golem Titânico de Sal", "Víbora Titânica"], boss: "Príncipe Titânico do Oásis",
    caveTheme: ct("Santuário Titânico", "#181c18", "#040804", "#e8c840", ["Miragem Titã", "Serpente Solar Titã", "Gárgula Titã"], "Guardião Titânico da Ilusão") },
  { id: 248, name: "Geleira Titânica de Piche",   color: "#182028", accent: "#080c10", danger: 175, monsters: ["Monstro Titânico de Alcatrão", "Mamute Titânico", "Draugr Titânico"], boss: "Abominável Titânico do Piche",
    caveTheme: ct("Abismo Titânico de Piche", "#080810", "#040406", "#4a8a90", ["Morcego Titânico", "Espectro Titânico", "Slime Titânico"], "Pesadelo Titânico do Alcatrão") },
  { id: 249, name: "Cemitério Titânico dos Gigantes", color: "#4c4640", accent: "#241f1a", danger: 180, monsters: ["Esqueleto Titânico de Titã", "Abutre Titânico", "Cão Titânico de Ossos"], boss: "Ceifador Titânico de Gigantes",
    caveTheme: ct("Mausoléu Titânico Gigante", "#101014", "#040406", "#d09090", ["Anão Zumbi Titã", "Espectro Ancestral Titã", "Verme Titã de Ossos"], "Rei Titânico Esqueleto Titã") },
  { id: 250, name: "Selva Titânica de Cobre",     color: "#906038", accent: "#4c2e18", danger: 200, monsters: ["Aranha Titânica de Bronze", "Macaco Titânico Mecânico", "Pantera Titânica de Latão"], boss: "Colosso Titânico Autômato",
    caveTheme: ct("Fundição Titânica de Cobre", "#1a120c", "#080604", "#c88040", ["Engrenagem Titânica", "Golem Titânico de Bronze", "Rato Titânico de Metal"], "Forjador Titânico Mecânico") },
];


