// Island 4 — 34 biomas lendários e divinos de nível 200+.
// Cada um conta com 12 sub-andares de caverna/profundidade com estruturação única.

import type { Biome } from "./engine";

function ct(
  label: string,
  floor: string,
  wall: string,
  accent: string,
  monsters: string[],
  boss: string,
) {
  return { label, floor, wall, accent, monsters, boss };
}

export const ISLAND4_BIOMES: Biome[] = [
  {
    id: 501,
    name: "Nebulosa de Éter",
    color: "#a040ff",
    accent: "#3a0066",
    danger: 200,
    monsters: ["Anomalia Etérea", "Tejedor de Luz", "Vigia de Plasma"],
    boss: "Soberano do Éter",
    caveTheme: ct(
      "Coração da Nebulosa",
      "#140026",
      "#04000c",
      "#c080ff",
      ["Larva Cósmica", "Plasma Vivo", "Sombra de Éter"],
      "Matriarca Cósmica",
    ),
  },
  {
    id: 502,
    name: "Cataratas de Plasma",
    color: "#ff3080",
    accent: "#66002b",
    danger: 202,
    monsters: ["Elemental Voltaico", "Corrente Instável", "Espectro de Fusão"],
    boss: "O Protetor de Fusão",
    caveTheme: ct(
      "Fossa de Fusão",
      "#260010",
      "#0c0005",
      "#ff60a0",
      ["Centelha Instável", "Aranha de Plasma", "Verme de Fusão"],
      "Núcleo Estável",
    ),
  },
  {
    id: 503,
    name: "Vale do Silêncio Cósmico",
    color: "#202040",
    accent: "#0a0a1c",
    danger: 205,
    monsters: ["Silenciador Cego", "Eco de Vazio", "Gárgula de Antimatéria"],
    boss: "O Deus Silencioso",
    caveTheme: ct(
      "Templo da Quietude",
      "#050510",
      "#010105",
      "#4040a0",
      ["Ermitão do Silêncio", "Sentinela Muda", "Sombra Triste"],
      "Eco Supremo",
    ),
  },
  {
    id: 504,
    name: "Fresta do Horizonte de Eventos",
    color: "#0a0a0f",
    accent: "#020205",
    danger: 208,
    monsters: ["Atrator Gravitacional", "Distorção Temporal", "Caçador Singular"],
    boss: "Fronteira Infinita",
    caveTheme: ct(
      "Singularidade Estrita",
      "#000000",
      "#000000",
      "#ff3300",
      ["Estilhaço de Espaço", "Verme Gravitacional", "Nômade do Horizonte"],
      "O Devorador de Luz",
    ),
  },
  {
    id: 505,
    name: "Mar de Singularidades",
    color: "#120d24",
    accent: "#030208",
    danger: 210,
    monsters: ["Lula Quântica", "Medusa Gravitacional", "Kraken Gravitacional"],
    boss: "Tritão da Singularidade",
    caveTheme: ct(
      "Abismo Gravitacional",
      "#05030c",
      "#010004",
      "#7040ff",
      ["Medusa Menor", "Anguia Espacial", "Polvo Singular"],
      "Deus Leviatã",
    ),
  },
  {
    id: 506,
    name: "Arquipélago Quântico",
    color: "#00e5ff",
    accent: "#004b5c",
    danger: 212,
    monsters: ["Partícula Entrelaçada", "Fantasma da Probabilidade", "Espectro Súbito"],
    boss: "A Superposição Divina",
    caveTheme: ct(
      "Câmara Quântica",
      "#00181f",
      "#00080a",
      "#80f5ff",
      ["Flutuação de Vácuo", "Gato Estático", "Projetor Quântico"],
      "Anomalia Unificada",
    ),
  },
  {
    id: 507,
    name: "Planalto da Matéria Escura",
    color: "#18142c",
    accent: "#05030c",
    danger: 215,
    monsters: ["Gólem de Matéria Escura", "Sombra Inerte", "Anjo Entrópico"],
    boss: "Monarca de Matéria Escura",
    caveTheme: ct(
      "Santuário Escuro",
      "#0a0814",
      "#020105",
      "#5c40ff",
      ["Inércia Viva", "Servo de Matéria Escura", "Aranha Escura"],
      "Tejedor da Inércia",
    ),
  },
  {
    id: 508,
    name: "Bosque de Fótons",
    color: "#d4ff00",
    accent: "#4b5c00",
    danger: 218,
    monsters: ["Fada Laser", "Treant de Luz Solida", "Borboleta Radiante"],
    boss: "Coração de Aurora",
    caveTheme: ct(
      "Clareira de Cristal",
      "#181f00",
      "#080a00",
      "#eaff80",
      ["Centelha Solar", "Broto Radiante", "Prisma Vivo"],
      "O Heliocentrista",
    ),
  },
  {
    id: 509,
    name: "Glaciar de Antimatéria",
    color: "#00ffcc",
    accent: "#005c4b",
    danger: 220,
    monsters: ["Espectro de Aniquilação", "Draugr Quântico", "Yeti de Antimatéria"],
    boss: "Imperador do Caos Térmico",
    caveTheme: ct(
      "Cripta da Aniquilação",
      "#001f18",
      "#000a08",
      "#80ffe6",
      ["Draugr do Zero Absoluto", "Espectro Gélido", "Cristal de Flutuação"],
      "Rei da Aniquilação",
    ),
  },
  {
    id: 510,
    name: "Deserto de Poeira Estelar",
    color: "#ffe57f",
    accent: "#5c4b00",
    danger: 222,
    monsters: ["Golem de Poeira Estelar", "Sacerdote das Estrelas", "Serpente Nebular"],
    boss: "Faraó das Galáxias",
    caveTheme: ct(
      "Tumba das Estrelas",
      "#1f1a00",
      "#0a0800",
      "#ffe082",
      ["Múmia Nebular", "Escaravelho Estelar", "Sombra Astral"],
      "Sacerdote Eterno",
    ),
  },
  {
    id: 511,
    name: "Abismo do Hiperespaço",
    color: "#ff40ff",
    accent: "#5c005c",
    danger: 225,
    monsters: ["Navegador do Hiperespaço", "Besta Multidimensional", "Vigia de Fendas"],
    boss: "Rei do Hiperespaço",
    caveTheme: ct(
      "Fenda do Hiperespaço",
      "#1f001f",
      "#0a000a",
      "#ffa0ff",
      ["Verme do Hiperespaço", "Fada de Fendas", "Larva Multidimensional"],
      "Dragão Interdimensional",
    ),
  },
  {
    id: 512,
    name: "Santuário das Supernovas",
    color: "#ff6d00",
    accent: "#5c2000",
    danger: 228,
    monsters: ["Elemental de Supernova", "Diabrete de Radiação", "Dragão de Chamas Brancas"],
    boss: "Deus da Estrela Colapsada",
    caveTheme: ct(
      "Núcleo da Supernova",
      "#1f0a00",
      "#0a0300",
      "#ffab40",
      ["Anel de Chamas", "Elemental Radioativo", "Chama Infinita"],
      "Titã da Supernova",
    ),
  },
  {
    id: 513,
    name: "Trincheira da Gravidade Zero",
    color: "#607d8b",
    accent: "#263238",
    danger: 230,
    monsters: ["Draugr Flutuante", "Anomalia Sem Peso", "Sentinela Cinética"],
    boss: "Orbital Supremo",
    caveTheme: ct(
      "Estação de Flutuação",
      "#0f1416",
      "#050708",
      "#b0bec5",
      ["Aranha Orbital", "Flutuador Cego", "Golem sem Peso"],
      "Anomalia Orbital",
    ),
  },
  {
    id: 514,
    name: "Labirinto Crono-Causal",
    color: "#8d6e63",
    accent: "#3e2723",
    danger: 232,
    monsters: ["Cavaleiro de Ontem", "Sentinela de Amanhã", "Relógio de Areia Vivo"],
    boss: "Guardião do Tempo Infinito",
    caveTheme: ct(
      "Ampulheta de Sangue",
      "#1a100e",
      "#0a0605",
      "#d7ccc8",
      ["Espectro Cronológico", "Aranha de Areia", "Servo Temporal"],
      "Lich do Tempo",
    ),
  },
  {
    id: 515,
    name: "Fossa de Radiação Hawking",
    color: "#e040fb",
    accent: "#4a0072",
    danger: 235,
    monsters: ["Espectro de Radiação", "Aranha Cósmica", "Lich de Hawking"],
    boss: "Singularidade Alfa",
    caveTheme: ct(
      "Câmara de Radiação",
      "#120020",
      "#06000c",
      "#f4ff81",
      ["Pó Quântico", "Espectro Instável", "Micro-Buraco Negro"],
      "Rei da Radiação",
    ),
  },
  {
    id: 516,
    name: "Tundra de Hélio Líquido",
    color: "#80deea",
    accent: "#006064",
    danger: 238,
    monsters: ["Crio-Basilisco", "Golem Criogênico", "Espectro do Zero Absoluto"],
    boss: "Monarca Criogênico",
    caveTheme: ct(
      "Gruta Criogênica",
      "#002d32",
      "#000f11",
      "#e0f7fa",
      ["Rato Criogênico", "Aranha Crio", "Verme de Hélio"],
      "Coração do Gelo Quântico",
    ),
  },
  {
    id: 517,
    name: "Pântano Quasar",
    color: "#00b0ff",
    accent: "#004080",
    danger: 240,
    monsters: ["Besta de Quasar", "Bruxa de Plasma", "Naga Luminosa"],
    boss: "Estrela Quasar Suprema",
    caveTheme: ct(
      "Cripta Quasar",
      "#001026",
      "#00050c",
      "#80d8ff",
      ["Slime de Plasma", "Sombra de Quasar", "Espírito Luminoso"],
      "Hidra Quasar",
    ),
  },
  {
    id: 518,
    name: "Selva de Taquions",
    color: "#76ff03",
    accent: "#2e7d32",
    danger: 242,
    monsters: ["Onça de Taquions", "Naga Hiperveloz", "Caçador do Futuro"],
    boss: "Altar Taquiônico",
    caveTheme: ct(
      "Templo da Taquions",
      "#0e2300",
      "#040c00",
      "#b2ff59",
      ["Taquion Cego", "Naga Sombra", "Servo Taquiônico"],
      "Sacerdote Taquiônico",
    ),
  },
  {
    id: 519,
    name: "Penhascos Entrópicos",
    color: "#78909c",
    accent: "#37474f",
    danger: 245,
    monsters: ["Águia Entrópica", "Gárgula de Decaimento", "Coro da Desordem"],
    boss: "Serafim da Entropia",
    caveTheme: ct(
      "Santuário Desfeito",
      "#161c1e",
      "#070a0b",
      "#cfd8dc",
      ["Espectro Entrópico", "Gárgula Ruída", "Vigia Caído"],
      "Serafim Desintegrado",
    ),
  },
  {
    id: 520,
    name: "Ruínas da Primeira Estrela",
    color: "#fffde7",
    accent: "#f57f17",
    danger: 248,
    monsters: ["Cavaleiro Primordial", "Estátua Solar", "Legionário Arcaico"],
    boss: "Deus da Primeira Estrela",
    caveTheme: ct(
      "Panteão Arcaico",
      "#201c00",
      "#0c0a00",
      "#fff59d",
      ["Legionário Fantasma", "Servo Primordial", "Anjo das Ruínas"],
      "Senador Primordial",
    ),
  },
  {
    id: 521,
    name: "Vulcão de Quarks",
    color: "#ff1744",
    accent: "#b71c1c",
    danger: 250,
    monsters: ["Elemental de Quarks", "Dragão Subatômico", "Lobo de Fogo Nuclear"],
    boss: "Senhor dos Quarks",
    caveTheme: ct(
      "Forja Subatômica",
      "#200307",
      "#0c0102",
      "#ff8a80",
      ["Quark Solto", "Salamandra Subatômica", "Chama Atômica"],
      "Núcleo de Quarks",
    ),
  },
  {
    id: 522,
    name: "Cordilheira das Supercordas",
    color: "#e040fb",
    accent: "#4a0072",
    danger: 252,
    monsters: ["Wyvern Vibratório", "Yeti das Dimensões", "Arqueiro Multidimensional"],
    boss: "Dragão das Supercordas",
    caveTheme: ct(
      "Câmara das Vibrações",
      "#120020",
      "#06000c",
      "#f4ff81",
      ["Servo Vibratório", "Fada Vibratória", "Aranha das Dimensões"],
      "Dragão da Vibração Máxima",
    ),
  },
  {
    id: 523,
    name: "Desfiladeiro Dimensional",
    color: "#651fff",
    accent: "#311b92",
    danger: 255,
    monsters: ["Fera das Dobras", "Basilisco Dimensional", "Bandoleiro de Fendas"],
    boss: "Wyrm do Dobramento",
    caveTheme: ct(
      "Fenda do Dobramento",
      "#0d0326",
      "#04010c",
      "#b388ff",
      ["Escaravelho de Dobras", "Larva Dimensional", "Sombra de Dobras"],
      "Wyrm Menor",
    ),
  },
  {
    id: 524,
    name: "Jardins da Energia Escura",
    color: "#1a237e",
    accent: "#0d47a1",
    danger: 258,
    monsters: ["Treant Negro", "Lobisomem do Vácuo", "Fada da Energia Escura"],
    boss: "Rei dos Jardins do Caos",
    caveTheme: ct(
      "Micélio do Caos",
      "#050a1f",
      "#01030a",
      "#8c9eff",
      ["Cogumelo do Vácuo", "Servo de Energia Escura", "Fada Menor do Caos"],
      "Rainha Fúngica do Vácuo",
    ),
  },
  {
    id: 525,
    name: "Templo do Vácuo Quântico",
    color: "#006064",
    accent: "#002426",
    danger: 260,
    monsters: ["Guerreiro do Vácuo", "Sentinela de Vácuo", "Eco do Vácuo"],
    boss: "Guardião Supremo do Templo",
    caveTheme: ct(
      "Sanctum do Vácuo",
      "#000f10",
      "#000404",
      "#80deea",
      ["Sentinela Menor", "Eco Sombrio", "Projetor de Vácuo"],
      "Lich de Vácuo",
    ),
  },
  {
    id: 526,
    name: "Arquitetura dos Precursores",
    color: "#004d40",
    accent: "#001a14",
    danger: 262,
    monsters: ["Autômato Precursor", "Sentinela Estelar", "Vigia de Metal"],
    boss: "O Olho Precursor",
    caveTheme: ct(
      "Núcleo Precursor",
      "#000c0a",
      "#000403",
      "#a7ffeb",
      ["Engrenagem Precursora", "Aranha de Metal", "Servo Mecânico"],
      "Motor Divino",
    ),
  },
  {
    id: 527,
    name: "Cemitério de Galáxias",
    color: "#37474f",
    accent: "#1a237e",
    danger: 265,
    monsters: ["Espectro Galáctico", "Lich de Galáxias", "Anjo Morto"],
    boss: "Deus da Morte Estelar",
    caveTheme: ct(
      "Cripta Estelar",
      "#070a16",
      "#02030a",
      "#b0bec5",
      ["Ossada Galáctica", "Espectro Menor", "Rato do Cemitério"],
      "Rei-Lich Galáctico",
    ),
  },
  {
    id: 528,
    name: "Abóboda Celeste Infinita",
    color: "#01579b",
    accent: "#002140",
    danger: 268,
    monsters: ["Servo da Abóboda", "Anjo Infinito", "Serafim da Luz"],
    boss: "Herald Divino Celeste",
    caveTheme: ct(
      "Santuário do Infinito",
      "#000814",
      "#000206",
      "#4fc3f7",
      ["Gárgula Celeste", "Anjo Menor Celeste", "Coro Divino Celeste"],
      "Serafim Celeste",
    ),
  },
  {
    id: 529,
    name: "Fronteira do Multiverso",
    color: "#12005e",
    accent: "#0a0033",
    danger: 270,
    monsters: ["Clone de Outro Universo", "Paradoxo Vivo", "Tejedor Multidimensional"],
    boss: "O Criador do Multiverso",
    caveTheme: ct(
      "Câmara do Paradoxo",
      "#030013",
      "#010006",
      "#b388ff",
      ["Paradoxo Menor", "Sombra Tridimensional", "Aranha Multiverso"],
      "Anomalia do Criador",
    ),
  },
  {
    id: 530,
    name: "Oásis de Neutrinos",
    color: "#00e676",
    accent: "#006020",
    danger: 272,
    monsters: ["Lula de Neutrinos", "Sereia Luminosa", "Estrela Quântica"],
    boss: "Leviatã Luminoso",
    caveTheme: ct(
      "Fossa Quântica",
      "#001f0a",
      "#000a03",
      "#69f0ae",
      ["Sereia Fantasma", "Anguia de Neutrinos", "Casco Luminoso"],
      "Leviatã Menor Luminoso",
    ),
  },
  {
    id: 531,
    name: "Garganta Gravitacional",
    color: "#212121",
    accent: "#0d0d0d",
    danger: 275,
    monsters: ["Golem de Atração", "Gárgula de Peso", "Distorção Gravitacional"],
    boss: "Colosso Gravitacional",
    caveTheme: ct(
      "Coração da Garganta",
      "#050505",
      "#010101",
      "#ffffff",
      ["Estilhaço de Peso", "Aranha de Peso", "Sentinela de Atração"],
      "Forjador de Gravidade",
    ),
  },
  {
    id: 532,
    name: "Fenda Cósmica Reversa",
    color: "#6a1b9a",
    accent: "#4a0072",
    danger: 278,
    monsters: ["Lich Invertido", "Esqueleto Reverso", "Anjo Negro Reverso"],
    boss: "O Anti-Criador Reverso",
    caveTheme: ct(
      "Cripta Invertida",
      "#120020",
      "#06000c",
      "#e040fb",
      ["Servo Reverso", "Espectro Reverso", "Rato Reverso"],
      "Rei-Lich Invertido",
    ),
  },
  {
    id: 533,
    name: "Mar de Vidro Estelar",
    color: "#00b0ff",
    accent: "#0060b0",
    danger: 280,
    monsters: ["Elemental de Vidro", "Harpia de Cristal", "Marinheiro Cristalino"],
    boss: "Leviatã de Vidro Estelar",
    caveTheme: ct(
      "Fossa de Vidro",
      "#001026",
      "#00050c",
      "#80d8ff",
      ["Espírito de Vidro", "Tritão de Vidro", "Casco Amaldiçoado"],
      "Leviatã Menor de Vidro",
    ),
  },
  {
    id: 534,
    name: "Trono do Vazio Primordial",
    color: "#ffe082",
    accent: "#ff8f00",
    danger: 300,
    monsters: ["Serafim Negro", "Coro do Vazio", "Arauto Divino"],
    boss: "Aethes, o Caos Encarnado",
    caveTheme: ct(
      "Sanctum do Vazio Primordial",
      "#1c1400",
      "#0a0700",
      "#ffd54f",
      ["Herald Menor do Vazio", "Servo do Caos", "Coro Divino do Vazio"],
      "Prece do Caos",
    ),
  },
];
